[project]
name = "re-fairdice"
version = "0.1.0"
description = "Replication study of FairDICE"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.4.2",
    #    "gymnasium[mujoco]>=1.2.3",
    "gymnasium>=1.2.3",
    "imageio>=2.37.2",
    "matplotlib>=3.10.8",
    "mujoco==2.3.3",
    "pyarrow>=22.0.0",
    "torch>=2.9.1",
    "torchinfo>=1.8.0",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.11",
    "ty>=0.0.11",
]
